# .github/workflows/rss_fetcher.yml (Updated with EOD HD API Token)

name: Fetch and Analyze News Feeds

on:
  schedule:
    # Run every hour at the 0th minute (e.g., 1:00, 2:00, 3:00)
    # This schedule is suitable for the EOD HD API Free Plan (10 news/hour)
    - cron: '0 * * * *'
  
  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure you have a requirements.txt file in your repository
          pip install -r requirements.txt

      - name: Run worker script
        env:
          # --- ส่วนที่เพิ่มเข้ามา ---
          # This line injects the secret into the environment
          EOD_HD_API_TOKEN: ${{ secrets.EOD_HD_API_TOKEN }}
          
          # Secrets เดิมที่ต้องมีอยู่
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: python worker.py
