name: Fetch and Analyze RSS Feeds

on:
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ใช้ requirements.txt เพื่อให้เวอร์ชันตรงกัน
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # --- รันสคริปต์ทดสอบตัวเล็กแทน ---
      - name: Run Minimal Test Script
        run: python test_feed.py