# .github/workflows/rss_fetcher.yml (Final Version)
name: Fetch and Analyze RSS Feeds

on:
  schedule:
    # รันทุกๆ ชั่วโมง.
    - cron: '0 * * * *'
  
  # อนุญาตให้รันแบบ manual
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ติดตั้งจาก requirements.txt ที่สะอาดแล้ว
          pip install -r requirements.txt

      - name: Run worker script
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: python worker.py